export { default as WelcomePage } from "./welcomePage"
export { default as LoginPage } from "./loginPage"
export { default as PlayersPage } from "./playersPage"
export { default as SocialLinkPage } from "./socialLinkPage"
export { default as CameraPage } from "./cameraPage"