export { default as WelcomePage } from "./welcomePage"
export { default as LoginPage } from "./loginPage"
export { default as PlayersPage } from "./playersPage"
export { default as SocialLinkPage } from "./socialLinkPage"
export { default as CameraPage } from "./cameraPage"
export { default as ParticipationPage } from "./ParticipationPage"
export { default as ScorePage } from "./ScorePage"